# Generated by Django 4.1.7 on 2023-03-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_category_delete_ads_delete_categories_ad_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='slug',
        ),
    ]
